<%@ Page Title="Welcome" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WingtipToys._Default" %>
<%@ Import Namespace="WingtipToys.Models" %>
<%@ Import Namespace="WingtipToys" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <h1><%: Title %>.</h1>
    <h2>Wingtip Toys can help you find the perfect gift.</h2>
    <p class="lead">We're all about transportation toys. You can order 
            any of our toys today. Each toy listing has detailed 
            information to help you choose the right toy.</p>

    <table id="recTable" style="width:100%;">
        <tbody>
            <tr>
                <td><b>Top Sellers</b></td>
            </tr>
        </tbody>
    </table>

    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.10.2.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub.
            var recommend = $.connection.signalrHub;
            // Create a function that the hub can call to broadcast recommendations.
            recommend.client.broadcastMessage = function (prodID, prod, im, price, catID) {
                // Add the product recommendation to the page.
                $('#recTable').append('<td><a href="/Product/' + prod + '"><img src=\'/Catalog/Images/Thumbs/' + im +
                    '\' width="100" height="75" border="1" /></a><br /><a href="/Product/' + prod + '">' + prod + '</a><br /><span><b>Price: </b>$' +
                    price + '</span><br /><a href="/AddToCart.aspx?productID=' + prodID + '"><span class="ProductListItem"><b>Add To Cart<b></span></a></td>');

            };
            // Start the connection.
            $.connection.hub.start().done(function () {
                // TODO: Query database.
                // Call the Send method on the hub.
                recommend.server.send(1, "Convertible Car", "carconvert.png", 22.50, 1);
                recommend.server.send(2, "Old-time Car", "carearly.png", 15.95, 1);
                recommend.server.send(3, "Fast Car", "carfast.png", 32.99, 1);
            })
        });

    </script>

</asp:Content>
